# Generated by Django 2.2 on 2019-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('likes', models.TextField(help_text="喜欢吃的菜关键字，使用'|'分割，eg.宫保鸡丁|孜然肥牛")),
                ('dislikes', models.TextField(help_text="不喜欢吃的菜关键字，使用'|'分割，eg.宫保鸡丁|孜然肥牛")),
                ('online', models.BooleanField(default=True)),
            ],
        ),
    ]
